version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - mvn clean package
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn package
artifacts:
  files:
  - target/helloworld-1.0.jar
